//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentsDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstrumentsDB()
        {
            this.OrderBookDBs = new HashSet<OrderBookDB>();
        }
    
        public long Id { get; set; }
        public string Symbol { get; set; }
        public long SecurityTypeId { get; set; }
    
        public virtual SecurityTypeDB SecurityTypeDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBookDB> OrderBookDBs { get; set; }
    }
}
