//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBookDB
    {
        public long Id { get; set; }
        public string Position { get; set; }
        public long Quantity { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public double Price { get; set; }
        public long InstrumentsId { get; set; }
        public Nullable<double> FairPrice { get; set; }
        public Nullable<double> ProfitLoss { get; set; }
        public Nullable<double> Delta { get; set; }
        public Nullable<double> Theta { get; set; }
        public Nullable<double> Gamma { get; set; }
        public Nullable<double> Vega { get; set; }
        public Nullable<double> Rho { get; set; }
    
        public virtual InstrumentsDB InstrumentsDB { get; set; }
    }
}
