//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockDB()
        {
            this.OptionsDBs = new HashSet<OptionsDB>();
        }
    
        public long Id { get; set; }
        public string Issuer { get; set; }
        public string Symbol { get; set; }
        public double LastTradedPrice { get; set; }
        public double HistoricalVolatility { get; set; }
        public bool IsTradable { get; set; }
        public string ISIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionsDB> OptionsDBs { get; set; }
    }
}
